# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FossaNx < Formula
  desc "High-performance FOSSA license scanning for NX monorepos"
  homepage "https://github.com/kamalesh-seervi/fossa-nx"
  version "1.1.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Kamalesh-Seervi/fossa-nx/releases/download/v1.1.1/fossa-nx_1.1.1_Darwin_x86_64.tar.gz"
      sha256 "2cee00d2dd9c68154d7d69a288d93bfb024d072ec6900a5e6d05ae31badfbb73"

      def install
        bin.install "fossa-nx"
      end
    end
    on_arm do
      url "https://github.com/Kamalesh-Seervi/fossa-nx/releases/download/v1.1.1/fossa-nx_1.1.1_Darwin_arm64.tar.gz"
      sha256 "885f603688ed0277339245072fbf04bd577d7c58dbc8f60dd6ea84905c64303d"

      def install
        bin.install "fossa-nx"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Kamalesh-Seervi/fossa-nx/releases/download/v1.1.1/fossa-nx_1.1.1_Linux_x86_64.tar.gz"
        sha256 "7ae2e3857edfac817152fca9ca54a4240a2098ccc5076d13b8e9fa800c9ac3d3"

        def install
          bin.install "fossa-nx"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Kamalesh-Seervi/fossa-nx/releases/download/v1.1.1/fossa-nx_1.1.1_Linux_arm64.tar.gz"
        sha256 "01d9fc4dc20a9c1a8a78eb086de20e008dae621563a60686ff6f9fb75f84a44f"

        def install
          bin.install "fossa-nx"
        end
      end
    end
  end

  test do
    system "#{bin}/fossa-nx", "--version"
  end
end
