# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FossaNx < Formula
  desc "High-performance FOSSA license scanning for NX monorepos"
  homepage "https://github.com/kamalesh-seervi/fossa-nx"
  version "1.2.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Kamalesh-Seervi/fossa-nx/releases/download/v1.2.4/fossa-nx_1.2.4_Darwin_x86_64.tar.gz"
      sha256 "d23ea2c42c8509718e9491dc1234947a44cabb5f27442210406d1b80fa7ed35b"

      def install
        bin.install "fossa-nx"
      end
    end
    on_arm do
      url "https://github.com/Kamalesh-Seervi/fossa-nx/releases/download/v1.2.4/fossa-nx_1.2.4_Darwin_arm64.tar.gz"
      sha256 "3b6f6af1963f921d3aa252c24318bf92bae0fddcf7c1adb2955a385e80de5aa9"

      def install
        bin.install "fossa-nx"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Kamalesh-Seervi/fossa-nx/releases/download/v1.2.4/fossa-nx_1.2.4_Linux_x86_64.tar.gz"
        sha256 "ddef550e12b8410d2d615f242756abdce5f50bcbd8bb559e9539248cd156e6ab"

        def install
          bin.install "fossa-nx"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Kamalesh-Seervi/fossa-nx/releases/download/v1.2.4/fossa-nx_1.2.4_Linux_arm64.tar.gz"
        sha256 "e2e2af43be63e7166f39417e25112d4d0f818669a49f0f33e412852ba55d17d4"

        def install
          bin.install "fossa-nx"
        end
      end
    end
  end

  test do
    system "#{bin}/fossa-nx", "--version"
  end
end
